# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02cc3f6851681bc049e92a343d3c1dda12cb56eec91eec59c3d6305e722b6b3073257ec7ce0ede61f4a21300f6063eac3245f66a0b9e5d8cd514f16a757a3693

test:
  secret_key_base: b2073ffb22a2015d6d8eb14efc05731ee4be350cc6e72eab9b14d09bf1abba11fb68ea3ad8589e2ea92901ba577c68884f9884df4af4b42884f23a91b798334d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
